### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Yanxin97** [gloryhry/radar2pointcloud#2]
感谢作者公开多传感器数据集。Onedrive上的数据貌似有一部分重合了。 我想使用绿色轨迹段的数据做一些感知任务。请问一下作者方便分享更多的雷达数据吗？

**Comment by gloryhry** [comment]
这边一共采集了3段路径的数据，每段路径都采集了两遍。数据集原本是想用于测试毫米波雷达定位算法的，因此没有感知结果的标注。我现在已经毕业，暂时无法采集更多的数据了。

**Comment by Yanxin97** [comment]
原来如此，感谢你的回复。
